apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yangmc-test
  name: ping-pong-deployment
spec:
  selector:
    matchLabels:
      app: ping-pong
  replicas: 2
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: registry.cn-qingdao.aliyuncs.com/yangmc/k8s-test:1.0.0
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  namespace: yangmc-test
  name: ping-pong-service
spec:
  selector:
    app: ping-pong
  #type: ClusterIP
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30555
