apiVersion: v1
kind: Pod
metadata:
  namespace: yangmc-test
  name: mongo-pod
  labels:
    app: mongo
spec:
  containers:
  - name: mongo
    image: registry.cn-qingdao.aliyuncs.com/yangmc/mongo:1.0.0
    ports:
    - containerPort: 27017
    volumeMounts:
      - mountPath: /data/db
        name: mongo-db
  volumes:
    - name: mongo-db
      emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  namespace: yangmc-test
  name: mongo-service
spec:
  selector:
    app: mongo
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017